export const colors = {
  yellow: '#E3B53C',
  orange: '#E3823C',
  red: '#E33C3C',
  white: '#ffffff',
  black: '#000000',
  green: '#1ab932',
  blue: '#1877F2',
  grey: '#808080',
  lightGrey: '#D3D3D3',
  lightDark: '#23203F',
  dark: '#141326',
  transparentYellow: 'rgba(227, 181, 60, 0.3)',
  transparent: 'transparent',
  gradientColor: '#E84040'
};

export const darkColors = {
  primary: colors.yellow,
  secondary: colors.orange,
  text: colors.white,
  background: colors.dark,
  secondaryBackground: '#201E43',
  white: colors.white,
  black: colors.black,
  orange: colors.orange,
  error: colors.red,
  success: colors.green,
  warning: colors.yellow,
  info: colors.yellow,
  inputBorder: colors.white,
  disabled: colors.lightGrey,
  outline: colors.grey,
  rippleColor: colors.transparentYellow,
  primaryGradient: [colors.yellow, colors.red],
  secondaryGradient: [colors.orange, colors.red],
};

export const lightColors = {
  primary: colors.yellow,
  secondary: colors.orange,
  text: colors.black,
  background: colors.white,
  secondaryBackground: colors.lightDark,
  white: colors.white,
  black: colors.black,
  orange: colors.orange,
  error: colors.red,
  success: colors.green,
  warning: colors.yellow,
  info: colors.yellow,
  inputBorder: colors.black,
  disabled: colors.lightGrey,
  outline: colors.grey,
  rippleColor: colors.transparentYellow,
  primaryGradient: [colors.yellow, colors.red],
  secondaryGradient: [colors.orange, colors.red],
};
